import React, { useState } from "react";
import { toast } from "react-toastify";
import { accessLevels } from "../../dummy_data/userAccountData";
import "../styles/AddUserModal.css";

interface AddUserModalProps {
    isOpen: boolean;
    isClosing: boolean;
    formData: {
        empId: string;
        firstName: string;
        middleName: string;
        lastName: string;
        username: string;
        password: string;
        confirmPassword: string;
        accessLevel: string;
    };
    onClose: () => void;
    onChange: (field: string, value: string) => void;
    onSave: () => void;
}

const AddUserModal: React.FC<AddUserModalProps> = ({
    isOpen,
    isClosing,
    formData,
    onClose,
    onChange,
    onSave,
}) => {
    const [isLoading, setIsLoading] = useState(false);

    if (!isOpen) return null;

    const validateForm = (): boolean => {
        if (!formData.firstName.trim()) {
            toast.error("First Name is required");
            return false;
        }

        if (!formData.lastName.trim()) {
            toast.error("Last Name is required");
            return false;
        }

        if (!formData.username.trim()) {
            toast.error("Username is required");
            return false;
        }

        if (!formData.password) {
            toast.error("Password is required");
            return false;
        }

        if (formData.password.length < 6) {
            toast.error("Password must be at least 6 characters");
            return false;
        }

        if (!formData.confirmPassword) {
            toast.error("Confirm Password is required");
            return false;
        }

        if (formData.password !== formData.confirmPassword) {
            toast.error("Passwords do not match");
            return false;
        }

        if (!formData.accessLevel) {
            toast.error("Access Level is required");
            return false;
        }

        return true;
    };

    const handleSave = async () => {
        if (!validateForm()) {
            return;
        }

        setIsLoading(true);

        try {
            // Simulate API call
            await new Promise(resolve => setTimeout(resolve, 1000));

            toast.success("User account created successfully!");
            
            // Reset form and close modal
            onSave();
            onClose();
        } catch (error) {
            toast.error("Failed to create user account. Please try again.");
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div
            className={`add-user-modal ${isClosing ? 'closing' : ''}`}
            onClick={e => e.stopPropagation()}
        >
                <div className="add-user-modal-header">
                    <h2 className="add-user-modal-title">Add New User Account</h2>
                    <button className="add-user-modal-close" onClick={onClose} disabled={isLoading}>
                        <svg fill="none" stroke="currentColor" viewBox="0 0 24 24" width="24" height="24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                    </button>
                </div>

                <div className="add-user-modal-content">
                    <div className="add-user-modal-form">
                        {/* First Row */}
                        <div className="add-user-modal-row">
                            <div className="add-user-modal-col">
                                <label className="add-user-modal-label">Employee ID</label>
                                <input
                                    type="text"
                                    className="add-user-modal-input"
                                    value={formData.empId}
                                    placeholder="Auto-generated by system"
                                    disabled={true}
                                />
                            </div>
                            <div className="add-user-modal-col">
                                <label className="add-user-modal-label">First Name *</label>
                                <input
                                    type="text"
                                    className="add-user-modal-input"
                                    value={formData.firstName}
                                    onChange={e => onChange('firstName', e.target.value)}
                                    placeholder="Enter first name"
                                    disabled={isLoading}
                                />
                            </div>
                        </div>

                        {/* Second Row */}
                        <div className="add-user-modal-row">
                            <div className="add-user-modal-col">
                                <label className="add-user-modal-label">Middle Name</label>
                                <input
                                    type="text"
                                    className="add-user-modal-input"
                                    value={formData.middleName}
                                    onChange={e => onChange('middleName', e.target.value)}
                                    placeholder="Enter middle name"
                                    disabled={isLoading}
                                />
                            </div>
                            <div className="add-user-modal-col">
                                <label className="add-user-modal-label">Last Name *</label>
                                <input
                                    type="text"
                                    className="add-user-modal-input"
                                    value={formData.lastName}
                                    onChange={e => onChange('lastName', e.target.value)}
                                    placeholder="Enter last name"
                                    disabled={isLoading}
                                />
                            </div>
                        </div>

                        {/* Third Row */}
                        <div className="add-user-modal-row">
                            <div className="add-user-modal-col">
                                <label className="add-user-modal-label">Username *</label>
                                <input
                                    type="text"
                                    className="add-user-modal-input"
                                    value={formData.username}
                                    onChange={e => onChange('username', e.target.value)}
                                    placeholder="Enter username"
                                    disabled={isLoading}
                                />
                            </div>
                            <div className="add-user-modal-col">
                                <label className="add-user-modal-label">Access Level *</label>
                                <select
                                    className="add-user-modal-input add-user-modal-select"
                                    value={formData.accessLevel}
                                    onChange={e => onChange('accessLevel', e.target.value)}
                                    disabled={isLoading}
                                >
                                    {accessLevels.map(level => (
                                        <option key={level} value={level}>{level}</option>
                                    ))}
                                </select>
                            </div>
                        </div>

                        {/* Fourth Row */}
                        <div className="add-user-modal-row">
                            <div className="add-user-modal-col">
                                <label className="add-user-modal-label">Password *</label>
                                <input
                                    type="password"
                                    className="add-user-modal-input"
                                    value={formData.password}
                                    onChange={e => onChange('password', e.target.value)}
                                    placeholder="Enter password"
                                    disabled={isLoading}
                                />
                            </div>
                            <div className="add-user-modal-col">
                                <label className="add-user-modal-label">Confirm Password *</label>
                                <input
                                    type="password"
                                    className="add-user-modal-input"
                                    value={formData.confirmPassword}
                                    onChange={e => onChange('confirmPassword', e.target.value)}
                                    placeholder="Confirm password"
                                    disabled={isLoading}
                                />
                            </div>
                        </div>
                    </div>
                </div>

                <div className="add-user-modal-footer">
                    <button className="add-user-modal-btn-cancel" onClick={onClose} disabled={isLoading}>
                        Cancel
                    </button>
                    <button className="add-user-modal-btn-save" onClick={handleSave} disabled={isLoading}>
                        {isLoading ? "Adding..." : "Add User"}
                    </button>
                </div>
            </div>
    );
};

export default AddUserModal;
