/**
 * Transaction type and static sample data for the Transactions page.
 * Replace with API fetch when backend is ready.
 */

export interface Transaction {
  category: string;
  transactionRef: string;
  date: string;
  payee: string;
  particulars: string;
  vesselPrincipal: string;
  etd: string;
  currency: string;
  amount: number;
  referenceErfp: string;
  branchToIssueMc: string;
  fundingAccount: string;
  batch: string;
  driveFileLink: string;
  supportingDocs: string;
}

export const transactionsData: Transaction[] = [
  {
    category: 'Category 1',
    transactionRef: 'TRX001',
    date: '2026-01-20',
    payee: 'John Doe',
    particulars: 'Purchase of goods',
    vesselPrincipal: 'Vessel A',
    etd: '2026-01-25',
    currency: 'USD',
      amount: 500.00,
    referenceErfp: 'eRFP001',
    branchToIssueMc: 'Branch A',
    fundingAccount: 'FA001',
    batch: 'Batch 1',
    driveFileLink: 'https://link-to-file.com',
    supportingDocs: 'https://docs-link.com',
  },
  {
    category: 'Category 2',
    transactionRef: 'TRX002',
    date: '2026-01-21',
    payee: 'Jane Smith',
    particulars: 'Service payment',
    vesselPrincipal: 'Vessel B',
    etd: '2026-01-26',
    currency: 'PHP',
      amount: 42000.00,
    referenceErfp: 'eRFP002',
    branchToIssueMc: 'Branch B',
    fundingAccount: 'FA002',
    batch: 'Batch 2',
    driveFileLink: 'https://link-to-file2.com',
    supportingDocs: 'https://docs-link2.com',
  },
  {
    category: 'Category 1',
    transactionRef: 'TRX003',
    date: '2026-01-22',
    payee: 'Bob Johnson',
    particulars: 'Equipment purchase',
    vesselPrincipal: 'Vessel C',
    etd: '2026-01-27',
    currency: 'USD',
      amount: 1200.00,
    referenceErfp: 'eRFP003',
    branchToIssueMc: 'Branch C',
    fundingAccount: 'FA003',
    batch: 'Batch 1',
    driveFileLink: 'https://link-to-file3.com',
    supportingDocs: 'https://docs-link3.com',
  },
  {
    category: 'Category 3',
    transactionRef: 'TRX004',
    date: '2026-01-23',
    payee: 'Marine Supplies Co',
    particulars: 'Bunkering and provisions',
    vesselPrincipal: 'Vessel D',
    etd: '2026-01-28',
    currency: 'USD',
      amount: 3400.00,
    referenceErfp: 'eRFP004',
    branchToIssueMc: 'Branch A',
    fundingAccount: 'FA004',
    batch: 'Batch 2',
    driveFileLink: 'https://link-to-file4.com',
    supportingDocs: 'https://docs-link4.com',
  },
  {
    category: 'Category 2',
    transactionRef: 'TRX005',
    date: '2026-01-24',
    payee: 'Port Authority Ltd',
    particulars: 'Port dues and fees',
    vesselPrincipal: 'Vessel A',
    etd: '2026-01-29',
    currency: 'USD',
      amount: 1850.00,
    referenceErfp: 'eRFP005',
    branchToIssueMc: 'Branch B',
    fundingAccount: 'FA005',
    batch: 'Batch 3',
    driveFileLink: 'https://link-to-file5.com',
    supportingDocs: 'https://docs-link5.com',
  },
  {
    category: 'Category 1',
    transactionRef: 'TRX006',
    date: '2026-01-25',
    payee: 'Global Freight Inc',
    particulars: 'Cargo handling charges',
    vesselPrincipal: 'Vessel E',
    etd: '2026-01-30',
    currency: 'USD',
      amount: 2200.00,
    referenceErfp: 'eRFP006',
    branchToIssueMc: 'Branch C',
    fundingAccount: 'FA001',
    batch: 'Batch 1',
    driveFileLink: 'https://link-to-file6.com',
    supportingDocs: 'https://docs-link6.com',
  },
  {
    category: 'Category 3',
    transactionRef: 'TRX007',
    date: '2026-01-26',
    payee: 'Philippine Shipyard',
    particulars: 'Dry dock repairs',
    vesselPrincipal: 'Vessel B',
    etd: '2026-02-01',
    currency: 'PHP',
      amount: 125000.00,
    referenceErfp: 'eRFP007',
    branchToIssueMc: 'Branch A',
    fundingAccount: 'FA006',
    batch: 'Batch 4',
    driveFileLink: 'https://link-to-file7.com',
    supportingDocs: 'https://docs-link7.com',
  },
  {
    category: 'Category 2',
    transactionRef: 'TRX008',
    date: '2026-01-27',
    payee: 'Crew Management Ltd',
    particulars: 'Crew wages and allotments',
    vesselPrincipal: 'Vessel C',
    etd: '2026-02-02',
    currency: 'USD',
      amount: 8900.00,
    referenceErfp: 'eRFP008',
    branchToIssueMc: 'Branch B',
    fundingAccount: 'FA002',
    batch: 'Batch 2',
    driveFileLink: 'https://link-to-file8.com',
    supportingDocs: 'https://docs-link8.com',
  },
  {
    category: 'Category 1',
    transactionRef: 'TRX009',
    date: '2026-01-28',
    payee: 'Insurance Partners',
    particulars: 'Marine insurance premium',
    vesselPrincipal: 'Vessel D',
    etd: '2026-02-03',
    currency: 'USD',
      amount: 4200.00,
    referenceErfp: 'eRFP009',
    branchToIssueMc: 'Branch C',
    fundingAccount: 'FA003',
    batch: 'Batch 1',
    driveFileLink: 'https://link-to-file9.com',
    supportingDocs: 'https://docs-link9.com',
  },
  {
    category: 'Category 3',
    transactionRef: 'TRX010',
    date: '2026-01-29',
    payee: 'Tech Marine Solutions',
    particulars: 'Navigation equipment upgrade',
    vesselPrincipal: 'Vessel E',
    etd: '2026-02-04',
    currency: 'USD',
      amount: 5600.00,
    referenceErfp: 'eRFP010',
    branchToIssueMc: 'Branch A',
    fundingAccount: 'FA004',
    batch: 'Batch 5',
    driveFileLink: 'https://link-to-file10.com',
    supportingDocs: 'https://docs-link10.com',
  },
];
